search/urls.py
from django.urls import path

from .views import SearchProductListView

urlpatterns = [
    path('', SearchProductListView.as_view(), name='query'),
]

shopzing/urls.py
from .views import contact_page, HomePage
from accounts.views import LoginView, RegisterView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from wishlist.views import wishlist_home, wishlist_detail_api_view
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    # path('wishlist/', WishListView.as_view(), name='wishlist'),
    path('accounts/', RedirectView.as_view(url='/account')),
    path('account/', include(('accounts.urls', 'accounts'), namespace = 'account')),
    path('accounts/', include('accounts.passwords.urls')),
    path('contact/', contact_page, name='contact'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('', include(('accounts.urls', 'accounts'), namespace = 'accounts')),
    # path('', include('accounts.passwords.urls')),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),
    path('api/wishlist/', wishlist_detail_api_view, name='api-wishlist'),
    path('wishlist/', include(('wishlist.urls', 'wishlist'), namespace = 'wishlist')),
    path('', include(('products.urls', 'products'), namespace = 'products')),
    path('search/', include(('search.urls', 'search'), namespace = 'search')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
import os
from django.db import models
from .utils import unique_slug_generator
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.db.models import Q






class ProductQuerySet(models.QuerySet):
    def discounted(self):
        return self.filter(discounted=True, active=True)

    # def new(self):
    #     now = timezone.now()
    #     created = self.objects.all()
    #     print(created)
    #     result = created - now
    #     if result.days <= -7:
    #         return self.filter(active=True)
    #     return self.filter(discounted=True, active=True)

    def active(self):
        return self.filter(active=True)

    def search(self, query):
        lookups = (Q(title__icontains=query) |
          Q(weight__icontains=query) |
          Q(tag__title__icontains=query))
        return self.filter(lookups).distinct()

    def detail(self, query):
        return self.filter(Q(slug__icontains=query))

    def to_display(self):
        return self.filter(to_display=True)

    





class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()


    def discounted(self):
        return self.get_queryset().discounted()


    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().to_display().search(query)

    def detail(self, query):
        return self.get_queryset().detail(query)

    




def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    return 'products/{shop}/{name}{ext}'.format(shop=instance.shop, name=name, ext=ext)


class Product(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, unique=True)
    weight = models.CharField(max_length=50, null=True)
    description = models.TextField(blank=True)
    shop = models.CharField(max_length=50, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=00.00)
    discounted_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    discounted_until = models.DateTimeField(blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    to_display = models.BooleanField(default=False)
    discounted = models.BooleanField(default=False)
    brand_logo = models.ImageField(upload_to=upload_image_path ,blank=True, null=True, editable=True)

    class Meta:
       ordering = ['id']
    
    objects = ProductManager()

    # def first_image(self):
    #     # code to determine which image to show. The First in this case.
    #     return self.images[0]

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug': self.title})
        # return '/products/{slug}/'.format(slug=self.slug)

    def __str__(self):
        return self.title

def product_pre_save_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_reciever, sender=Product)


def product_title_capitalize_pre_save_reciever(sender, instance, *args, **kwargs):
    instance.title = instance.title.upper()

pre_save.connect(product_title_capitalize_pre_save_reciever, sender=Product)



def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    return 'products/{shop}/{name}{ext}'.format(shop=instance.shop, name=name, ext=ext)


class ProductImage(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_image_path ,blank=True, null=True, editable=True)
    # image_height = models.PositiveIntegerField(null=True, blank=True, editable=False, default="100")
    # image_width = models.PositiveIntegerField(null=True, blank=True, editable=False, default="100")


    @property
    def shop(self):
        return self.product.shop

    # def get_image(self):
    #     return self.image.first()

templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


<!--Font awsome CDN-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">


<!-- JQuery confirm CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">






<!-- <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"> -->


<!-- Nice select -->

<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css"> -->

<!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->

templates/base/custom_css_login.html
<style>
    /* NOTE: The styles were added inline because Prefixfree needs access to your styles and they must be inlined if they are on local disk! */

    * {
box-sizing: border-box;
}



form {
background: #17a2b8;
margin-left: 25%;
margin-right:25%;
margin-bottom: 25%;
margin-top: 12%;
width: 30%;
overflow: hidden;
position: fixed;
left: 15%;
box-shadow: 0 5px 10px 5px rgba(0, 0, 0, 0.2);
}

form:after {
content: "";
display: block;
position: absolute;
height: 1px;
width: 100px;
left: 20%;
top: 0;
}

form:before {
content: "";
display: block;
position: absolute;
width: 8px;
height: 5px;
border-radius: 50%;
left: 34%;
top: -7px;
box-shadow: 0 0 6px 4px #fff;
}

.inset {
padding: 20px;
border-top: 1px solid #19191a;
}

form h1 {
font-size: 1rem;
text-shadow: 0 1px 0 black;
text-align: center;
padding: 15px 0;
border-bottom: 1px solid black;
position: relative;
}

form h1:after {
content: "";
display: block;
width: 250px;
height: 100px;
position: absolute;
top: 0;
left: 50px;
pointer-events: none;
transform: rotate(70deg);
background: linear-gradient(50deg, rgba(255, 255, 255, 0.15), rgba(0, 0, 0, 0));
}

label {
color: white;
display: block;
padding-bottom: 9px;
}

input[type=text],
input[type=password],
input[type=email] {
width: 100%;
padding: 8px 5px;
background: white;
border: 1px solid #222;
box-shadow: 0 1px 0 rgba(255, 255, 255, 0.1);
border-radius: 0.3em;
margin-bottom: 20px;
}


.p-container {
padding: 0 20px 20px 20px;
}

.p-container:after {
clear: both;
display: table;
content: "";
}

.p-container span {
display: block;
font-size: 1rem;
float: left;
color: whitesmoke;
padding-top: 8px;
}

input[type=submit] {
padding: 5px 20px;
border: 1px solid rgba(0, 0, 0, 0.4);
text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.4);
box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.3), inset 0 10px 10px rgba(255, 255, 255, 0.1);
border-radius: 0.3em;
background:black;
color: white;
float: right;
font-weight: bold;
cursor: pointer;
font-size: 13px;
}

input[type=submit]:hover {
box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.3), inset 0 -10px 10px rgba(255, 255, 255, 0.1);
}

input[type=text]:hover,
input[type=password]:hover,
input[type=email]:hover,
label:hover ~ input[type=text],
label:hover ~ input[type=password],
label:hover ~ input[type=email] {
background:gainsboro;
}



  </style>

templates/base/js.html
{% load static %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


<!-- JQuery confirm JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>


<!-- Login form -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>


<!-- Django Secure AJAX -->

<script src="{% static 'js/csrf.ajax.js' %}"></script>


<!-- Custom JS -->

<script src="{% static 'js/shopzing.js' %}"></script>




<!-- New JS for testing -->

<script src="{% static 'js/active.js' %}"></script>

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'products:product_list' as product_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
<!-- {% url 'register' as register_url %} -->
{% url 'contact' as contact_url %}
{% url 'account:home' as account_url %}
{% url 'wishlist:home' as wishlist_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-info mb-3">
  <div class="container">
        <a class="navbar-brand" href="{{ home_url }}">
          <img src="/media/products/site_logo.png" class="d-inline-block align-top" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == home_url %}active{% endif %}">
              <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == product_url %}active{% endif %}">
              <a class="nav-link" href="{{ product_url }}">Products</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item {% if request.path == account_url %}active{% endif %}" href="{{ account_url }}">Home</a>
                <a class="dropdown-item" href="#">Preferences</a>
                <a class="dropdown-item" href="#">Notifications</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
              </div>
            </li>
            {% else %}
            
            <!-- <li class="nav-item {% if request.path == register_url %}active{% endif %}">
              <a class="nav-link" href="{{ register_url }}">Register</a>
            </li> -->
            <li class="nav-item {% if request.path == login_url %}active{% endif %}">
              <a class="nav-link" href="{{ login_url }}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
              <a class="nav-link" href="{{ contact_url }}">Contact Us</a>
            </li>
            <li class="nav-item {% if request.path == wishlist_url %}active{% endif %}">
                <a class="nav-link" href="{{ wishlist_url }}"><span class="navbar-wish-count">{{ request.session.wishlist_items }}</span> <i class="fas fa-bell"></i></a>
              </li>
          </ul>
          {% include 'search/snippets/search_form.html' %}
        </div>
  </div>
      </nav>

templates/base/navbar1.html
{% url 'home' as home_url %}
{% url 'products:product_list' as product_url %}
{% url 'products:new_products' as newproducts_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
<!-- {% url 'register' as register_url %} -->
{% url 'contact' as contact_url %}
{% url 'account:home' as account_url %}
{% url 'wishlist:home' as wishlist_url %}

    

{% include 'base/css.html' %}
<div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fas fa-window-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row mt-5">
                <div class="col-12">
                    
                    {% include 'search/snippets/search_form.html' %}
                    
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="shopzing-navbar-brand">
                    <a href="{{ home_url }}"></a>
                    <img src="/media/products/site_logo.png" class="d-inline-block align-top" alt="">
            </div>
            <!-- Navbar Toggler -->
            <div class="shopzing-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area">
        <nav class="navbar">
            <!-- Logo -->
            <div class="logo">
                <!-- <a href="index.html"><img src="img/core-img/logo.png" alt=""></a> -->
                <a href="{{ home_url }}"></a>
                <img src="/media/products/site_logo.png" class="d-inline-block align-top" alt="">
            </div>
            <!-- shopzing Nav -->
            <nav class="shopzing-nav">
                <ul>
                    <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                    <a href="{{ home_url }}">Home</a>
                    </li>
                    <li class="nav-item {% if request.path == product_url %}active{% endif %}">
                    <a href="{{ product_url }}">Products</a>
                    </li>
                    <li class="nav-item {% if request.path == wishlist_url %}active{% endif %}">
                    <a  href="{{ wishlist_url }}">Wishlist  <span class="navbar-wish-count">{{ request.session.wishlist_items }}</span>  <i class="fas fa-bell"></i></a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item {% if request.path == account_url %}active{% endif %}">
                        <a href="{{ account_url }}">Account</a>
                    </li>
                    <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
                    <a href="{{ logout_url }}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                    <a href="{{ login_url }}">Login</a>
                    </li>
                  {% endif %}
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="shopzing-btn-group mt-30 mb-100">
                <a href="{{ home_url }}" class="btn shopzing-btn mb-15">%Discount%</a>
                <a href="{{ newproducts_url }}" class="btn shopzing-btn active">New this week</a>
            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a href="#" class="fav-nav"><img src="" alt=""> Favourite</a>
                <a href="#" class="search-nav"><img src="" alt=""> Search</a>
                <!-- {% include 'search/snippets/search_form.html' %} -->
            </div>
            <!-- Social Button -->
            <!-- <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div> -->
            
        </header>
        
          
        
    </div>
    
        
    
        

templates/base/pagination.html
{% if is_paginated %}
    <nav aria-label="Page navigation" class="mt-5">  
        <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">begin</span>
          </a>
        </li>
        {% endif %}
        
        {% for n in page_obj.paginator.page_range %}
          {% if page_obj.number == n %}
            <li class="page-item active">
              <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
            </li>
          {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
          {% endif %}
        {% endfor %}
        
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">end</span>
            </a>
          </li>
          {% endif %}   
        </ul>
         </nav>
        
    {% endif %} 