products/urls.py
from django.urls import path

from .views import ProductListView, ProductDetailSlugView, NewProductsListView#, ProductDiscountedListView, ProductDiscountedDetailView,

urlpatterns = [
    # path('discounted/', ProductDiscountedListView.as_view(), name='discounted'),
    # path('discounted/<pk>/', ProductDiscountedDetailView.as_view(), name='detail_discounted'),
    path('products/new/', NewProductsListView.as_view(), name='new_products'),
    path('products/', ProductListView.as_view(), name='product_list'),
    # path('products/<pk>/', ProductDetailView.as_view(), name='details'),
    path('products/<slug>/', ProductDetailSlugView.as_view(), name='detail'),
    
]

search/urls.py
from django.urls import path

from .views import SearchProductListView

urlpatterns = [
    path('', SearchProductListView.as_view(), name='query'),
]

products/models.py
import os
from django.db import models
from .utils import unique_slug_generator
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from django.db.models import Q






class ProductQuerySet(models.QuerySet):
    def discounted(self):
        return self.filter(discounted=True, active=True)

    # def new(self):
    #     now = timezone.now()
    #     created = self.objects.all()
    #     print(created)
    #     result = created - now
    #     if result.days <= -7:
    #         return self.filter(active=True)
    #     return self.filter(discounted=True, active=True)

    def active(self):
        return self.filter(active=True)

    def search(self, query):
        lookups = (Q(title__icontains=query) |
          Q(weight__icontains=query) |
          Q(tag__title__icontains=query))
        return self.filter(lookups).distinct()

    def detail(self, query):
        return self.filter(Q(slug__icontains=query))

    def to_display(self):
        return self.filter(to_display=True)

    





class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()


    def discounted(self):
        return self.get_queryset().discounted()


    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().to_display().search(query)

    def detail(self, query):
        return self.get_queryset().detail(query)

    




def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    return 'products/{shop}/{name}{ext}'.format(shop=instance.shop, name=name, ext=ext)


class Product(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, unique=True)
    weight = models.CharField(max_length=50, null=True)
    description = models.TextField(blank=True)
    shop = models.CharField(max_length=50, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=00.00)
    discounted_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    discounted_until = models.DateTimeField(blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    to_display = models.BooleanField(default=False)
    discounted = models.BooleanField(default=False)
    brand_logo = models.ImageField(upload_to=upload_image_path ,blank=True, null=True, editable=True)

    class Meta:
       ordering = ['id']
    
    objects = ProductManager()

    # def first_image(self):
    #     # code to determine which image to show. The First in this case.
    #     return self.images[0]

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug': self.title})
        # return '/products/{slug}/'.format(slug=self.slug)

    def __str__(self):
        return self.title

def product_pre_save_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_reciever, sender=Product)


def product_title_capitalize_pre_save_reciever(sender, instance, *args, **kwargs):
    instance.title = instance.title.upper()

pre_save.connect(product_title_capitalize_pre_save_reciever, sender=Product)



def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    return 'products/{shop}/{name}{ext}'.format(shop=instance.shop, name=name, ext=ext)


class ProductImage(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_image_path ,blank=True, null=True, editable=True)
    # image_height = models.PositiveIntegerField(null=True, blank=True, editable=False, default="100")
    # image_width = models.PositiveIntegerField(null=True, blank=True, editable=False, default="100")


    @property
    def shop(self):
        return self.product.shop

    # def get_image(self):
    #     return self.image.first()

products/views.py
from .models import Product,ProductImage
from tags.models import Tag
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.views.generic import DetailView, ListView
from django.utils.text import slugify

from wishlist.models import WishList
from analytics.mixins import ObjectViewedMixin
# from analytics.signals import object_viewed_signal
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.utils import timezone
from datetime import timedelta



# class ProductDiscountedListView(ListView):
#     template_name = 'products/product_list.html'
   
#     def get_queryset(self, *args, **kwargs):
#         request = self.request
#         return Product.objects.all().discounted()


class ProductDiscountedDetailView(DetailView):
    template_name = 'products/product_detail_discounted.html'
    
    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().discounted()


class ProductListView(ListView):
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = 'products'  # Default: object_list
    paginate_by = 8 
   


    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        request = self.request
        if request.user.is_authenticated:
            wishlist_obj, new_obj = WishList.objects.new_or_get(request)
            context['wishlist'] = wishlist_obj
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super(ProductListView, self).get_queryset()
        queryset = Product.objects.all()
        paginator = Paginator(queryset, self.paginate_by)
        page = self.request.GET.get('page')
        request = self.request
        if request.user.is_authenticated:
            wishlist_obj, new_obj = WishList.objects.new_or_get(request)
            # wishlist_obj = WishList.objects.all().get(user=request.user)
            if request.user == wishlist_obj.user:
                request.session['wishlist_items'] = wishlist_obj.products.count()
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        
        return queryset

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     return Product.objects.all()

    # def get_context_data(self, **kwargs):
    #     context = super(ProductListView, self).get_context_data(**kwargs) 
    #     qs = Product.objects.all().to_display()
    #     paginator = Paginator(qs, self.paginate_by)

    #     page = self.request.GET.get('page')

    #     try:
    #         products = paginator.page(page)
    #     except PageNotAnInteger:
    #         products = paginator.page(1)
    #     except EmptyPage:
    #         products = paginator.page(paginator.num_pages)

    #     context['qs'] = products
    #     return context

    


class ProductDetailSlugView(ObjectViewedMixin,ListView):
    model = Product
    template_name = 'products/product_detail.html'
    
    #queryset = Product.objects.filter(slug__icontains=slug)
    #queryset = ProductTag.objects.all()
    #print(queryset)

    # def get_object(self, *args, **kwargs):
    #     request = self.request
    #     slug = self.kwargs.get('slug')
    #     # queryset = Product.objects.filter(slug__icontains=slug)
    #     instance = get_object_or_404(Product, slug__icontains=slug)
    #     return instance

    
    # def get_context_data(self, **kwargs):
    #     context = super(ProductDetailSlugView, self).get_context_data(**kwargs)
    #     slug = self.kwargs.get('slug')
    #     # # query = Product.objects.filter(slug__icontains=slug)
    #     context['query'] = Product.objects.filter(slug__icontains=slug)
    #     #     print(Product.objects.filter(slug__icontains=slug))
    #     # return context
    #     return context
    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     #slug = self.kwargs.get('slug')
    #     query = self.kwargs.get('slug')
    #     context = Product.objects.filter(title__icontains=query)
    #     # context['image'] = ProductImage.objects.all()
    #     return context

    def get_context_data(self, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(**kwargs)
        request = self.request
        if request.user.is_authenticated: 
            wishlist_obj, new_obj = WishList.objects.new_or_get(request)
            context['wishlist'] = wishlist_obj
            return context
        else:
            query = self.kwargs.get('slug')
            query = slugify(query)
            instance = Product.objects.detail(query)
            instance_obj = instance.first()
            context['wishlist'] = instance
            return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = self.kwargs.get('slug')
        query = slugify(query)
        instance = Product.objects.detail(query)
        instance_obj = instance.first()
        return instance
    


   

class ProductDetailView(DetailView):
    #model = Product
    template_name = 'products/product_detail.html'
   
    def get_context_data(self, **kwargs):
        context = super(ProductDetailView,self).get_context_data(**kwargs)
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instance = Product.objects.get_by_id(pk)
        if instance is None:
            raise Http404("Product does not exist!")
        return instance
    
    

class NewProductsListView(ListView):
    template_name = 'products/new_product_list.html'
    
    def get_queryset(self, *args, **kwargs):
        now = timezone.now() + timedelta(days=1)
        last_seven = now - timedelta(days=7)
        created = Product.objects.filter(timestamp__range=[last_seven.date(), now.date()]).active()
        return created
    

products/templates/products/new_product_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
            
    {% include 'base/navbar1.html' with brand_name='ShopZing' %}
    
    </div>
    <div class="row">
     
    {% if object_list.counter > 0 %} 
            
        {% for obj in object_list %}
        {% if obj.to_display %}
        <div class="col-2 product-items">
            
            {% include 'products/snippets/card.html' with instance=obj %}
            
            {% if forloop.counter|divisibleby:4 %}
            </div></div> <div class='row'>
            {% else %}
            </div>
            {% endif %}
            
                
        {% endif %}   
        {% endfor %}
    {% else %}
    <p class="lead">No new items this week</p>
    {% endif %}
    
</div>

  
<div class="col-1 paginator">
    {% include 'base/pagination.html' %}
</div>
   
{% endblock content %}

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  {% include 'base/navbar1.html' with brand_name='ShopZing' %}
  <div class="container">
     
    {% for object in object_list  %}
        

  {% if object.active and object.to_display %}
  <div class="product-detail">
    <h1>{{ object.title }}</h1> </br>
    {{ object.weight }} </br></br></br>
    {{ object.description|linebreaks }} </br>

    {% if user.is_authenticated %}
    {% include 'products/snippets/update_wishlist.html' with product=object wishlist=wishlist %}
    {% endif %}

  {% endif %}
    
    {% if object.productimage_set.all %}
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
      {% for product_image in object.productimage_set.all %}
      
          <div class="{% if forloop.counter == 1 %}carousel-item active{% else %}carousel-item{% endif %}" id="slide{{ forloop.counter }}">
              <a target="_blank" href="{{ product_image.image.url }}">
            <img src="{{product_image.image.url}}" class="d-block w-100" alt="{{ object.title }}">
          </div>
    
        <!-- <div class="carousel-item">
            <a target="_blank" href="{{ product_image.image.url }}">
          <img src="{{product_image.image.url}}" class="d-block w-100" alt="{{ object.title }}">
        </div> -->
        {% if forloop.counter > 1 %}
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
        {% endif %}
        {% endfor %}
      </div>
      </div>
    {% endif %}
    </div>
    
      {% endfor %}
      <div class="price-group">
          {% if object_list.count > 1 %}
        </div><div class="price-group">
          {% endif %}
          <div class="col-3 product-price">
          
          {% for object in object_list  %}
            
            
              
              
          {% if object.discounted %}
            <h4><span class="badge badge-info">Original: {{ object.price }} CZK</span></h4>
            <h2><span class="badge badge-danger">Super Price: {{ object.discounted_price }} CZK</span></h2>
            {% if object.discounted_until %}
              <h5><span class="badge badge-warning">Time left: {{ object.discounted_until|timeuntil }}</span></h5>
            {% endif %}
            
          {% else %}
            <h2><span class="badge badge-info">{{ object.price }} CZK</span></h2>
          {% endif %}
          <img class="img" src="{{ object.brand_logo.url }}" style="height: 100px" alt=""><hr/>
          {% endfor %}
        </div>
    </div>  
  </div>
  </div>  
</div>
  
 
{% endblock content %}

products/templates/products/product_detail_discounted.html
{% extends 'base.html' %}

{% block content %}

    {{ object.title }} </br>
    {{ object.weight }} </br>
    {{ object.description }} </br>

    {% if product.productimage_set.all %}

    {% for product_image in product.productimage_set.all %}
    <div class="profile-img-container" style="text-align: center">
        <img class="img" src="{{ product_image.image.url }}" style="height: 150px">
        <a target="_blank" href="{{ product_image.image.url }}">Link
            <!-- <span class="fa fa-expand fa-5x" style="color: darkcyan" aria-hidden="true"></span> -->
        </a>
    </div>
    {% endfor %}

    {% endif %}

{% endblock content %}

products/templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
    {% include 'base/navbar1.html' with brand_name='ShopZing' %}
    
    </div>
    <div class="row">
    {% for obj in object_list %}
    {% if obj.to_display %}
    <div class="col-2 product-items">
          
        {% include 'products/snippets/card.html' with instance=obj %}
        
        {% if forloop.counter|divisibleby:4 %}
        </div></div> <div class='row'>
        {% else %}
        </div>
        {% endif %}
        
            
     {% endif %}   
    {% endfor %}
    
</div>

  
<div class="col-1 paginator">
    {% include 'base/pagination.html' %}
</div>
   
{% endblock content %}